# プリコンパイルヘッダを指定
STDHEADER=main.h
LIBNAME  = map

SRC = \
	main.cpp           \
	plot_magnet.cpp    \
	plot_plasma.cpp    \
	misc.cpp           \

OBJ = $(SRC:%.cpp=$(OBJ_PATH)/%.$(OBJECT_EXP))
.SUFFIXES:.$(OBJECT_EXP).cpp

#.oファイルを置く場所
OBJ_PATH = object
VPATH    = $(OBJ_PATH)
